FROM node:22-alpine

# Install optional dependencies (like fs tools that help file watching work better)
RUN apk add --no-cache bash curl git

WORKDIR /app

COPY ./frontend/package*.json ./

# install devDependencies too (for ts-node-dev)
RUN npm install

# copy rest of the code
COPY ./frontend .

# expose if not already
EXPOSE 3000

# run dev script (with hot reload)
CMD ["npm", "run", "dev"]
