FROM node:22-slim

# Install sharp dependencies for Debian ARM
RUN apt-get update && apt-get install -y \
    bash \
    curl \
    git \
    libvips-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ./backend/package*.json ./

# Install devDependencies too (for ts-node-dev)
RUN npm install

# Copy rest of the code
COPY ./backend .

# Expose port
EXPOSE 1337

# Run dev script (with hot reload)
CMD ["npm", "run", "start:dev"]