FROM node:lts-alpine

RUN npm install -g npm@latest

RUN apk update && apk upgrade && apk add --no-cache bash curl git

WORKDIR /app

COPY ./backend/package*.json ./

# install devDependencies too (for ts-node-dev)
RUN npm install

# copy rest of the code
COPY ./backend .

# expose if not already
EXPOSE 1337

# run dev script (with hot reload)
CMD ["npm", "run", "start:dev"]
