/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AcceptDialog: typeof import('./components/basicUI/AcceptDialog.vue')['default']
    AddExerciseList: typeof import('./components/Exercise/AddExerciseList.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BackHeader: typeof import('./components/BackHeader.vue')['default']
    BottomNavigation: typeof import('./components/BottomNavigation.vue')['default']
    CreateExercise: typeof import('./components/Exercise/CreateExercise.vue')['default']
    EditExercise: typeof import('./components/Exercise/EditExercise.vue')['default']
    EditWorkout: typeof import('./components/Workout/EditWorkout.vue')['default']
    ExerciseList: typeof import('./components/Exercise/ExerciseList.vue')['default']
    ExitHeader: typeof import('./components/basicUI/ExitHeader.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HomeHeader: typeof import('./components/HomeHeader.vue')['default']
    MyWorkouts: typeof import('./components/MyWorkouts.vue')['default']
    ProgressBar: typeof import('./components/ProgressBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WeightAndRepsSettings: typeof import('./components/Workout/WeightAndRepsSettings.vue')['default']
  }
}
