/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AcceptDialog: typeof import('./components/basicUI/AcceptDialog.vue')['default']
    ActivityList: typeof import('./components/Settings/ActivityList.vue')['default']
    AddExerciseList: typeof import('./components/Exercise/AddExerciseList.vue')['default']
    AddGlobalExerciseList: typeof import('./components/Exercise/AddGlobalExerciseList.vue')['default']
    BackHeader: typeof import('./components/BackHeader.vue')['default']
    BottomNavigation: typeof import('./components/BottomNavigation.vue')['default']
    CreateExercise: typeof import('./components/Exercise/CreateExercise.vue')['default']
    CreateWorkout: typeof import('./components/Workout/CreateWorkout.vue')['default']
    EditExercise: typeof import('./components/Exercise/EditExercise.vue')['default']
    EditSetDialog: typeof import('./components/Session/EditSetDialog.vue')['default']
    EditWorkout: typeof import('./components/Workout/EditWorkout.vue')['default']
    EditWorkoutExercise: typeof import('./components/Workout/EditWorkoutExercise.vue')['default']
    ExerciseList: typeof import('./components/Exercise/ExerciseList.vue')['default']
    ExitHeader: typeof import('./components/basicUI/ExitHeader.vue')['default']
    HomeHeader: typeof import('./components/HomeHeader.vue')['default']
    ImageUpload: typeof import('./components/basicUI/ImageUpload.vue')['default']
    MyWorkouts: typeof import('./components/MyWorkouts.vue')['default']
    ProgressBar: typeof import('./components/ProgressBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SessionList: typeof import('./components/Settings/SessionList.vue')['default']
    TimerDialog: typeof import('./components/Session/TimerDialog.vue')['default']
    WeightAndRepsSettings: typeof import('./components/Workout/WeightAndRepsSettings.vue')['default']
    WorkoutExerciseCard: typeof import('./components/Session/WorkoutExerciseCard.vue')['default']
    WorkoutList: typeof import('./components/Settings/WorkoutList.vue')['default']
  }
}
