/*
 * Copyright (c) 2026 FalkenDev
 *
 * This file is part of Trainity.
 *
 * Trainity is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of
 * the License, or (at your option) any later version.
 *
 * You should have received a copy of the GNU Affero General Public
 * License along with Trainity. If not, see
 * <https://www.gnu.org/licenses/>.
 */

/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/AddWorkout': RouteRecordInfo<'/AddWorkout', '/AddWorkout', Record<never, never>, Record<never, never>>,
    '/Calendar': RouteRecordInfo<'/Calendar', '/Calendar', Record<never, never>, Record<never, never>>,
    '/LogActivity': RouteRecordInfo<'/LogActivity', '/LogActivity', Record<never, never>, Record<never, never>>,
    '/Login': RouteRecordInfo<'/Login', '/Login', Record<never, never>, Record<never, never>>,
    '/Onboarding': RouteRecordInfo<'/Onboarding', '/Onboarding', Record<never, never>, Record<never, never>>,
    '/Register': RouteRecordInfo<'/Register', '/Register', Record<never, never>, Record<never, never>>,
    '/Session': RouteRecordInfo<'/Session', '/Session', Record<never, never>, Record<never, never>>,
    '/SessionDetail': RouteRecordInfo<'/SessionDetail', '/SessionDetail', Record<never, never>, Record<never, never>>,
    '/SessionSummary': RouteRecordInfo<'/SessionSummary', '/SessionSummary', Record<never, never>, Record<never, never>>,
    '/Settings': RouteRecordInfo<'/Settings', '/Settings', Record<never, never>, Record<never, never>>,
    '/Statistics': RouteRecordInfo<'/Statistics', '/Statistics', Record<never, never>, Record<never, never>>,
    '/WorkoutDetails': RouteRecordInfo<'/WorkoutDetails', '/WorkoutDetails', Record<never, never>, Record<never, never>>,
    '/WorkoutDetailsOld': RouteRecordInfo<'/WorkoutDetailsOld', '/WorkoutDetailsOld', Record<never, never>, Record<never, never>>,
  }
}
